# Generated by Django 5.2 on 2025-04-16 09:03

import django.db.models.deletion
import verification.utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("registration_date", models.DateField()),
                (
                    "registration_number",
                    verification.utils.fields.EncryptedCharField(max_length=100),
                ),
                (
                    "address",
                    verification.utils.fields.EncryptedCharField(max_length=500),
                ),
                (
                    "contact_person",
                    verification.utils.fields.EncryptedCharField(max_length=255),
                ),
                ("number_of_employees", models.IntegerField()),
                (
                    "contact_phone",
                    verification.utils.fields.EncryptedCharField(max_length=50),
                ),
                ("email", verification.utils.fields.EncryptedCharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="departments",
                        to="verification.company",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "employee_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("current_role", models.CharField(max_length=255)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employees",
                        to="verification.company",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="verification.department",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RoleHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField(max_length=255)),
                ("date_started", models.DateField()),
                ("date_left", models.DateField(blank=True, null=True)),
                ("duties", models.CharField(max_length=1000)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_histories",
                        to="verification.company",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_histories",
                        to="verification.employee",
                    ),
                ),
            ],
        ),
    ]
