# Generated by Django 5.2 on 2025-04-13 16:28

import verification.utils.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("verification", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="contact_phone",
            field=verification.utils.fields.EncryptedCharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="company",
            name="email",
            field=verification.utils.fields.EncryptedCharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="company",
            name="registration_number",
            field=verification.utils.fields.EncryptedCharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="employee",
            name="employee_id",
            field=verification.utils.fields.EncryptedCharField(
                blank=True, max_length=100, null=True
            ),
        ),
    ]
