# Generated by Django 5.2 on 2025-04-13 21:24

import verification.utils.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "verification",
            "0002_alter_company_contact_phone_alter_company_email_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="address",
            field=verification.utils.fields.EncryptedCharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="company",
            name="contact_person",
            field=verification.utils.fields.EncryptedCharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="company",
            name="name",
            field=verification.utils.fields.EncryptedCharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="employee",
            name="name",
            field=verification.utils.fields.EncryptedCharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="rolehistory",
            name="duties",
            field=verification.utils.fields.EncryptedCharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="rolehistory",
            name="role",
            field=verification.utils.fields.EncryptedCharField(max_length=255),
        ),
    ]
