# Generated by Django 5.2 on 2025-04-14 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "verification",
            "0003_alter_company_address_alter_company_contact_person_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="employee",
            name="employee_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="rolehistory",
            name="duties",
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="rolehistory",
            name="role",
            field=models.CharField(max_length=255),
        ),
    ]
