# Generated by Django 5.2 on 2025-04-15 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("verification", "0004_alter_company_name_alter_employee_employee_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rolehistory",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="role_histories",
                to="verification.employee",
            ),
        ),
    ]
